---
title: "Plan of Future Development"
author: "Peter von Rohr"
date: "7/30/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Disclaimer
This document contains the plan for the future development in the project `QAAM` and is the result of a discussion with Sophie on 30.07.2018 and an introduction by Sophie on 31.07.2018 to the scripts and programs that are run during a routine genetic analysis.


## Current Status
As an example of the current status of the analysis routines, we are looking at the confluence page under https://qualitasag.atlassian.net/wiki/spaces/ZWS/pages/192970777/Anleitung+ZWS+Schlachtmerkmale. On this page the routine for the data analysis is described in a step-by-step procedure in the section entitled 'Ablauf' on the above mentioned confluence page. 


### Characterizing the steps
In this subsection, we try to group the different steps according to their properties. 

* A first category contains the steps that are executed manually by entering statements at the command-line prompt (Steps 1, 2, 7 and 8). This category includes the manual editing steps of input files or scripts. When following the steps that are given on the instructions page and by comparing the results to already existing versions of the input files or the scripts. These steps are already reproducible. The only negative point of these manual steps is that it is tedious to execute the steps and it is error-prone.
* The second category of steps describes which programs are to be started using which input. The steps in this category are easier to reproduce in terms of re-executing the commands to start the programs. But they are lacking a description of the results to what a reproducing run of the programs must be compared to. 


## Refactoring
It might be worthwhile thinking about the different changes that are needed in order to reach a code base that shows improved properties with respect to reproducibility. The required set of changes is determined by those parts of the current code base which do not show any properties of reproducibility.


## Puzzeling Questions
### Q1: Separation of master scripts into templates and executing code
The current versions of master scripts contain execution statements together with writing parameter files. Many of these details remain constant over the different instances of a given routine data analysis. Would it not be better to separate the constant parts of a parameter file into a template of this parameter file and use the script only to change the parts that depend on the different instances of a routine analysis?

### A1: Separation of executing code into scripts and constant config parts into templates
The reason for why this separation is necessary to keep reproducibility is because if we want to make small changes in the parts of the script that outputs the constant configuration files, such as the statistical model formulation for MiX99 and if running the complete master script takes a significant amount of time, then reproducibility can only be guaranteed, if the whole master script is run again with every small change. If the small changes are only done in the resulting parameter files, reproducibilty is broken. 

An alternative approach to keep reproducibility is to move the parts that are constant from the master script into a template and to this template the changes are applied and the parts of the analysis that involves the changes are repeated. 

Reproducibility can be installed by either looking at the time-stamps of the configuration templates and the log-files or by including the git version numbers of the used configuration file. 


